name: playx_version_update
description: Easily show material update dialog in Android or Cupertino dialog in IOS with support for Google play in app updates.
version: 1.0.0
homepage: https://sourcya.io
repository: https://github.com/playx-flutter/playx_version_update
issue_tracker: https://github.com/playx-flutter/playx_version_update/issues
screenshots:
  - description: 'This screenshot shows Google play flexible in app update flow'
    path: screenshots/screenshot7.png
  - description: 'This screenshot shows Android style update dialog.'
    path: screenshots/screenshot4.jpg
  - description: 'This screenshot shows Google play immediate in app update'
    path: screenshots/screenshot2.jpg
  - description: 'This screenshot shows IOS style update dialog.'
    path: screenshots/screenshot3.jpg
  - description: 'This screenshot shows update page.'
    path: screenshots/screenshot5.jpg
  - description: 'This screenshot shows Android style update dialog with release notes and force update enabled.'
    path: screenshots/screenshot6.jpg

topics:
    - playx
    - update
    - in-app-update
    - upgrade


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  playx_network: ^0.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.sourcya.playx_version_update
        pluginClass: PlayxVersionUpdatePlugin

platforms:
  android:
  ios:
